server:
  port: 8080
  servlet:
    context-path: /medicine

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/medicine_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
open:
  api:
    title: E-commerce_Service API Document
